# Generated by Django 3.1.7 on 2021-03-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresat', to='exercises_app.student')),
                ('to_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odbiorca', to='exercises_app.student')),
            ],
        ),
    ]
