# Generated by Django 3.1.7 on 2021-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(choices=[(0, '0%'), (0.05, '5%'), (0.08, '8%'), (0.23, '23%')]),
        ),
    ]
